### PR TITLE
Restore compatibility with 2024.1.0

### LINKED ISSUE #331: Not working in 2024.1.0
I just updated to the new Release of HomeAssistant,

the integration is failing to load.

Logger: homeassistant.loader
Source: loader.py:822
First occurred: 21:11:05 (1 occurrences)
Last logged: 21:11:05

Unexpected exception importing component custom_components.rct_power
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 822, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/rct_power/__init__.py", line 25, in <module>
    from .lib.entities import all_entity_descriptions
  File "/config/custom_components/rct_power/lib/entities.py", line 7, in <module>
    from .device_info_helpers import get_battery_device_info, get_inverter_device_info
  File "/config/custom_components/rct_power/lib/device_info_helpers.py", line 4, in <module>
    from .entity import RctPowerEntity
  File "/config/custom_components/rct_power/lib/entity.py", line 201, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
    _init_fn(all_init_fields,
  File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
    raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'object_infos' follows default argument

### PR DESCRIPTION
**Pull request by weltenwort**
## :memo: Summary

This changes the entity description dataclasses to be compatible with the changes made in https://github.com/home-assistant/core/pull/105211. It intentionally doesn't pull in any other changes so that users can choose to only install the fix. New features will be released in a follow-up version.

closes #331

### CODE REVIEW

**Comment by gt026328** [comment]
Thanks for fixing this issue. Great thing!
And what do I have to do now to get this update to my home-assistant running in a container?
Within HACS I do not get a update listet. As running in a container environment it is very hard for me to localize the dir. and files to be changed. 
Do I just have to copy the Integration in the HACS menu again and get the changed files to the right place?
Tx for advice
Tom

**Comment by knieshe1** [comment]
Bin Neuling
leider nicht so fit im programmieren
kommt eine neue Version von RCT-Power welche mit Version HA 2024.1.2 läuft.
Wie kann ich die Korrektur "einfach" durchführen

Danke im Voraus
Heinz

**Comment by weltenwort** [comment]
@gt026328 it took me just a bit more time to test everything and draft a release. Now HACS should offer an update to version 0.11.0.

**Comment by weltenwort** [comment]
@knieshe1 ich habe versucht Deine Frage in https://github.com/weltenwort/home-assistant-rct-power-integration/issues/338#issuecomment-1880172988 zu beantworten. Vmtl. warst Du auch einfach zu schnell für mich :wink:

**Pull request merged**
