### PR TITLE
Updating HACS badge

### PR DESCRIPTION
**Pull request by HrGaertner**
A very small change, but it did irritated me when i came across this package.

Thanks a lot for this great integration, it works perfectly

### CODE REVIEW

**Comment by weltenwort** [comment]
Thank you for contributing. How do you interpret the meaning of "default" vs "custom" in the badge? This project just inherited it from the cookie-cutter template.

**Comment by HrGaertner** [comment]
As far as I understood the hacs documentation default means if you search something in HACS it shows up (it is in the hacs default repository https://github.com/hacs/default (your integration is listed there))
Custom means it is hacs compatible but first one has to add the repository and then one can install the integration.

For reference the hacs documentation how to become a default repository: https://hacs.xyz/docs/publish/include

**Comment by weltenwort** [comment]
Makes sense, thanks for the explanation!

**Comment by HrGaertner** [comment]
Thanks for merging

**Pull request merged**
